title: Dmitry Babichev's webpage
author:
  name: Dmitry Babichev
  email: dimitry008@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Here you can find solution to some algorithmic problems, at the moment it is mainly leetcode problems.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - site_codeforces problems.md
 - site_leetcode problems.md
 - site_binarysearch problems.md
 - coding ideas.md
 - performance tricks.md

# Google Analytics
google_analytics: G-KR1GZKF62P


# Build settings
theme: minima
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-tagories

collections:
  binarysearch:
    output: true
  codeforces:
    ouptut: true
  leetcode:
    output: true
  